CREATE SCHEMA employees;
SET search_path = employees;

CREATE TYPE employee_gender AS ENUM (
    'M',
    'F',
    'X'
);

CREATE TABLE employee (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    birth_date date NOT NULL,
    first_name varchar(14) NOT NULL,
    last_name varchar(16) NOT NULL,
    gender employee_gender NOT NULL,
    hire_date date NOT NULL
);

CREATE TABLE department (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dept_name varchar(40) NOT NULL
);

CREATE TABLE department_employee (
    employee_id int NOT NULL REFERENCES employee,
    department_id int NOT NULL REFERENCES department,
    from_date date NOT NULL,
    to_date date NOT NULL,
    PRIMARY KEY (employee_id, department_id)
);

CREATE TABLE department_manager (
    employee_id int NOT NULL REFERENCES employee,
    department_id int NOT NULL REFERENCES department,
    from_date date NOT NULL,
    to_date date NOT NULL,
    PRIMARY KEY (employee_id, department_id)
);

CREATE TABLE salary (
    employee_id int NOT NULL REFERENCES employee,
    amount bigint NOT NULL,
    from_date date NOT NULL,
    to_date date NOT NULL,
    PRIMARY KEY (employee_id, from_date)
);

CREATE TABLE title (
    employee_id int NOT NULL REFERENCES employee,
    title character varying(50) NOT NULL,
    from_date date NOT NULL,
    to_date date NOT NULL,
    PRIMARY KEY (employee_id, title, from_date)
);