services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: index-lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./1_init_schema.sql:/docker-entrypoint-initdb.d/1_init_schema.sql
      - ./2_init_data.sql.gz:/docker-entrypoint-initdb.d/2_init_data.sql.gz
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

